{% set name = "gstools" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36ed5f11087a09952920a711e459988167d8d634b131c8a5187bebaf83ac0df5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.8.0
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - gstools-cython >=1,<2
    - numpy >=1.20.0
    - scipy >=1.1.0
    - emcee >=3.0.0
    - hankel >=1.0.0
    - pyevtk >=1.1.1
    - meshio >=5.1.0

test:
  imports:
    - gstools
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/GSTools
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'GSTools: A geostatistical toolbox.'
  description: |
    GeoStatTools provides geostatistical tools for various purposes:
    - random field generation
    - simple, ordinary, universal and external drift kriging
    - conditioned field generation
    - incompressible random vector field generation
    - (automatted) variogram estimation and fitting
    - directional variogram estimation and modelling
    - data normalization and transformation
    - many readily provided and even user-defined covariance models
    - metric spatio-temporal modelling
    - plotting and exporting routines
  doc_url: https://gstools.readthedocs.io
  dev_url: https://github.com/GeoStat-Framework/GSTools

extra:
  recipe-maintainers:
    - MuellerSeb
    - LSchueler
